### ISSUE TITLE
MMposeTopDownEstimator: name 'init_pose_model' is not defined

### ISSUE THREAD

**Issue by patrickESM** [openxrlab/xrmocap#110]
Hi there.

When running the demo after following the install instructions from https://github.com/openxrlab/xrmocap/blob/main/docs/en/installation.md i get the following error. The same error also occurs when running `pytest tests/`.

Looking forward to your help. Thanks a lot in advance.

`python tools/mview_mperson_topdown_estimator.py --estimator_config 'configs/mvpose_tracking/mview_mperson_topdown_estimator.py' --image_and_camera_param 'xrmocap_data/Shelf_50/image_and_camera_param.txt' --start_frame 300 --end_frame 350 --output_dir 'output/estimation' --enable_log_file`

`
load checkpoint from local path: weight/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
Traceback (most recent call last):
  File "/home/pschuelein/anaconda3/envs/xrmocap/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/pschuelein/projects/xrmocap/xrmocap/human_perception/keypoints_estimation/mmpose_top_down_estimator.py", line 50, in __init__
    self.pose_model = init_pose_model(**mmpose_kwargs)
NameError: name 'init_pose_model' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pschuelein/anaconda3/envs/xrmocap/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/pschuelein/projects/xrmocap/xrmocap/core/estimation/mview_mperson_topdown_estimator.py", line 111, in __init__
    self.kps2d_estimator = build_detector(kps2d_estimator)
  File "/home/pschuelein/projects/xrmocap/xrmocap/human_perception/builder.py", line 32, in build_detector
    return DETECTORS.build(cfg)
  File "/home/pschuelein/anaconda3/envs/xrmocap/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/pschuelein/anaconda3/envs/xrmocap/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
NameError: MMposeTopDownEstimator: name 'init_pose_model' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/mview_mperson_topdown_estimator.py", line 178, in <module>
    main(args)
  File "tools/mview_mperson_topdown_estimator.py", line 35, in main
    smpl_estimator = build_estimator(estimator_config)
  File "/home/pschuelein/projects/xrmocap/xrmocap/core/estimation/builder.py", line 32, in build_estimator
    return ESTIMATORS.build(cfg)
  File "/home/pschuelein/anaconda3/envs/xrmocap/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/pschuelein/anaconda3/envs/xrmocap/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
NameError: MultiViewMultiPersonTopDownEstimator: MMposeTopDownEstimator: name 'init_pose_model' is not defined`

**Comment by dwygs** [comment]
> Hi, i had a version missmatch with scipy module. When ignoring the pip warning of MMTrack regarding version missmatch the code worked fine. I leave it open in case you have a better solution to the problem. Feel free to close it though

i face the same trouble as your, how did you solved it?
