### ISSUE TITLE
ImportError: cannot import name 'Keypoints' from 'xrprimer.data_structure'

### ISSUE THREAD

**Issue by Billccx** [openxrlab/xrmocap#122]
运行
```
python tools/mview_mperson_topdown_estimator.py \
      --estimator_config 'configs/mvpose_tracking/mview_mperson_topdown_estimator.py' \
      --image_and_camera_param 'xrmocap_data/Shelf_50/image_and_camera_param.txt' \
      --start_frame 300 \
      --end_frame 350 \
      --output_dir 'output/estimation' \
      --enable_log_file
```

报错：
```
Traceback (most recent call last):
  File "tools/mview_mperson_topdown_estimator.py", line 17, in <module>
    from xrmocap.core.estimation.builder import build_estimator
  File "/home/xrmocap/xrmocap/core/estimation/__init__.py", line 3, in <module>
    from .mperson_smpl_estimator import MultiPersonSMPLEstimator
  File "/home/xrmocap/xrmocap/core/estimation/mperson_smpl_estimator.py", line 5, in <module>
    from xrprimer.data_structure import Keypoints
ImportError: cannot import name 'Keypoints' from 'xrprimer.data_structure' (/root/miniconda3/envs/xrmocap/lib/python3.8/site-packages/xrprimer/data_structure/__init__.py)
```

ImportError: cannot import name 'Keypoints' from 'xrprimer.data_structure'
安装过程完全按照教程，但出现以下问题，请问会是什么问题？谢谢

**Comment by LazyBusyYang** [comment]
Keypoints在XRPrimer-v0.7.0版本引入，您可以通过以下命令检查xrprimer的实际安装版本：
```
python -c "import xrprimer; print(xrprimer.__version__)"
```
如果结果低于0.7.0，请尝试通过pip安装最新版本的xrprimer.

**Comment by Billccx** [comment]
> Keypoints在XRPrimer-v0.7.0版本引入，您可以通过以下命令检查xrprimer的实际安装版本：
> 
> ```
> python -c "import xrprimer; print(xrprimer.__version__)"
> ```
> 
> 如果结果低于0.7.0，请尝试通过pip安装最新版本的xrprimer.

感谢您的回复，代码跑通了。另外请问openxrlab是否有官方组建的交流群？谢谢

**Comment by LazyBusyYang** [comment]
![IMG_1339](https://github.com/openxrlab/xrmocap/assets/26729379/636c2104-b8d5-4017-98f0-6ce8c44ba66f)
您可以通过这个二维码加入微信群聊
