### ISSUE TITLE
run single person demo failed

### ISSUE THREAD

**Issue by canghaiyunfan** [openxrlab/xrmocap#75]
```
2023-02-13 16:06:36,471 - __main__ - INFO - Estimating keypoints3d.
2023-02-13 16:06:36,471 - __main__ - ERROR - No one has been detected in any view.
Traceback (most recent call last):
  File "/home/code/xrmocap/tools/process_smc.py", line 214, in <module>
    main(args)
  File "/home/code/xrmocap/tools/process_smc.py", line 76, in main
    keypoints2d_list, keypoints3d, smpl_data = mview_sp_smpl_estimator.run(
  File "/home/code/xrmocap/xrmocap/core/estimation/mview_sperson_smpl_estimator.py", line 232, in run
    keypoints3d = self.estimate_keypoints3d(
  File "/home/code/xrmocap/xrmocap/core/estimation/mview_sperson_smpl_estimator.py", line 330, in estimate_keypoints3d
    raise AttributeError
AttributeError
```

cmd
```
python tools/process_smc.py \
	--estimator_config configs/humman_mocap/mview_sperson_smpl_estimator.py \
	--smc_path xrmocap_data/humman/p000127_a000007.smc \
	--output_dir xrmocap_data/humman/p000127_a000007_output \
	--visualize
````

**Comment by LazyBusyYang** [comment]
I have done the same thing like you, below is my command:
```bash
python tools/process_smc.py --smc_path HuMMan/smc/p000127_a000007.smc --output_dir HuMMan/xrmocap_output/ --visualize --disable_log_file
```
And I've got the correct results. Here are my visuailization results.

https://user-images.githubusercontent.com/26729379/218937913-48c35999-9978-4083-a066-a1a4d26d2a74.mp4

https://user-images.githubusercontent.com/26729379/218937986-17fe9952-0f2c-44c0-b1a1-5a505f04c057.mp4

Did you download your SMC data from our [getting_started section](https://github.com/openxrlab/xrmocap/blob/main/docs/en/getting_started.md#single-person)?

**Comment by LazyBusyYang** [comment]
Logs(except visualization logs):
```
2023-02-14 17:39:13,170 - __main__ - INFO - Estimating keypoints2d.
2023-02-14 17:39:13,170 - __main__ - INFO - Estimating keypoints2d.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:06<00:00, 12.74it/s]
2023-02-14 17:40:21,400 - __main__ - INFO - Estimating keypoints2d.
2023-02-14 17:40:21,400 - __main__ - INFO - Estimating keypoints2d.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:08<00:00,  1.11it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:12<00:00,  7.17it/s]
2023-02-14 17:41:37,498 - __main__ - INFO - Estimating keypoints2d.
2023-02-14 17:41:37,498 - __main__ - INFO - Estimating keypoints2d.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.13it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:01<00:00, 80.99it/s]
2023-02-14 17:42:46,503 - __main__ - INFO - Estimating keypoints2d.
2023-02-14 17:42:46,503 - __main__ - INFO - Estimating keypoints2d.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:11<00:00,  8.00it/s]
2023-02-14 17:43:59,411 - __main__ - INFO - Estimating keypoints2d.
2023-02-14 17:43:59,411 - __main__ - INFO - Estimating keypoints2d.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:08<00:00,  1.10it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:09<00:00,  9.42it/s]
2023-02-14 17:45:12,810 - __main__ - INFO - Estimating keypoints2d.
2023-02-14 17:45:12,810 - __main__ - INFO - Estimating keypoints2d.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:08<00:00,  1.10it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:13<00:00,  6.84it/s]
2023-02-14 17:46:29,787 - __main__ - INFO - Estimating keypoints2d.
2023-02-14 17:46:29,787 - __main__ - INFO - Estimating keypoints2d.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:08<00:00,  1.12it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:12<00:00,  6.90it/s]
2023-02-14 17:47:46,715 - __main__ - INFO - Estimating keypoints2d.
2023-02-14 17:47:46,715 - __main__ - INFO - Estimating keypoints2d.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:08<00:00,  1.07it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 243.27it/s]
2023-02-14 17:48:55,237 - __main__ - INFO - Estimating keypoints2d.
2023-02-14 17:48:55,237 - __main__ - INFO - Estimating keypoints2d.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:08<00:00,  1.12it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:02<00:00, 31.18it/s]
2023-02-14 17:50:01,606 - __main__ - INFO - Estimating keypoints2d.
2023-02-14 17:50:01,606 - __main__ - INFO - Estimating keypoints2d.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:08<00:00,  1.02it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:12<00:00,  7.01it/s]
2023-02-14 17:50:23,155 - __main__ - INFO - Estimating keypoints3d.
2023-02-14 17:50:23,155 - __main__ - INFO - Estimating keypoints3d.
2023-02-14 17:50:23,158 - __main__ - INFO - Selecting cameras.
2023-02-14 17:50:23,158 - __main__ - INFO - Selecting cameras.
2023-02-14 17:50:23,158 - __main__ - INFO - Using pre-selector for camera selection.
2023-02-14 17:50:23,158 - __main__ - INFO - Using pre-selector for camera selection.
2023-02-14 17:50:23,282 - __main__ - INFO - 
+-------------+-----------------------+
| Valid Views |         Pairs         |
+-------------+-----------------------+
|      0      | 0.0010137703810087016 |
|      1      |  0.00878600996874208  |
|      2      |  0.05989693334459745  |
+-------------+-----------------------+
2023-02-14 17:50:23,282 - __main__ - INFO - 
+-------------+-----------------------+
| Valid Views |         Pairs         |
+-------------+-----------------------+
|      0      | 0.0010137703810087016 |
|      1      |  0.00878600996874208  |
|      2      |  0.05989693334459745  |
+-------------+-----------------------+
2023-02-14 17:50:24,687 - __main__ - INFO - Selected cameras: [1, 2, 4, 7, 8, 9]
2023-02-14 17:50:24,687 - __main__ - INFO - Selected cameras: [1, 2, 4, 7, 8, 9]
2023-02-14 17:50:24,690 - __main__ - INFO - Selecting points.
2023-02-14 17:50:24,690 - __main__ - INFO - Selecting points.
2023-02-14 17:50:24,815 - __main__ - INFO - 
+-------------+----------------------+
| Valid Views |        Pairs         |
+-------------+----------------------+
|      0      | 0.013854861873785587 |
|      1      | 0.18619582664526485  |
|      2      | 0.42696629213483145  |
+-------------+----------------------+
2023-02-14 17:50:24,815 - __main__ - INFO - 
+-------------+----------------------+
| Valid Views |        Pairs         |
+-------------+----------------------+
|      0      | 0.013854861873785587 |
|      1      | 0.18619582664526485  |
|      2      | 0.42696629213483145  |
+-------------+----------------------+
2023-02-14 17:50:24,816 - __main__ - WARNING - There's no potential to search a higher threshold according to init_points_mask.
2023-02-14 17:50:24,816 - __main__ - WARNING - There's no potential to search a higher threshold according to init_points_mask.
2023-02-14 17:50:25,746 - __main__ - INFO - 
How many nans are found after mask: 2368
How many nans are interpolated: 2368
2023-02-14 17:50:25,746 - __main__ - INFO - 
How many nans are found after mask: 2368
How many nans are interpolated: 2368
   Iteration     Total nfev        Cost      Cost reduction    Step norm     Optimality   
       0              1         1.2756e+10                                    3.75e+11    
       1              2         2.9560e+09      9.80e+09       1.15e+00       4.66e+10    
       2              3         6.4636e+08      2.31e+09       1.87e+00       1.08e+10    
       3              4         1.4846e+08      4.98e+08       9.90e-01       1.86e+10    
       4              5         2.8791e+07      1.20e+08       5.01e-01       3.47e+09    
       5              6         9.5510e+06      1.92e+07       5.53e-01       7.10e+08    
       6              7         6.9842e+06      2.57e+06       3.26e-01       3.51e+08    
       7              8         3.7509e+06      3.23e+06       1.71e-01       1.61e+08    
       8              9         2.9951e+06      7.56e+05       1.12e-01       1.26e+08    
       9             11         2.5320e+06      4.63e+05       2.46e-02       3.51e+07    
      10             12         1.9455e+06      5.86e+05       3.46e-02       1.65e+07    
      11             13         1.9318e+06      1.37e+04       2.59e-02       6.30e+06    
      12             15         1.9296e+06      2.17e+03       1.02e-02       2.26e+06    
      13             16         1.9238e+06      5.84e+03       7.29e-03       1.80e+05    
      14             17         1.9236e+06      1.90e+02       1.02e-02       3.11e+05    
`ftol` termination condition is satisfied.
Function evaluations 17, initial cost 1.2756e+10, final cost 1.9236e+06, first-order optimality 3.11e+05.
optimization took 142.27 seconds
2023-02-14 17:52:48,093 - __main__ - INFO - Estimating SMPL.
2023-02-14 17:52:48,093 - __main__ - INFO - Estimating SMPL.
2023-02-14 17:52:48,110 - __main__ - INFO - epoch 0, stage 0
2023-02-14 17:52:48,110 - __main__ - INFO - epoch 0, stage 0
2023-02-14 17:52:48,422 - __main__ - INFO - [ftol=0.0001] Early stop at 2 iter!
2023-02-14 17:52:48,422 - __main__ - INFO - [ftol=0.0001] Early stop at 2 iter!
2023-02-14 17:52:48,434 - __main__ - INFO - 
+----------------------+------------+
|      Loss name       | Loss value |
+----------------------+------------+
|     shape_prior      |  0.000078  |
| keypoints3d_limb_len |  0.000873  |
|      total_loss      |  0.000951  |
|  default_optimizer   |  0.000951  |
+----------------------+------------+
2023-02-14 17:52:48,434 - __main__ - INFO - 
+----------------------+------------+
|      Loss name       | Loss value |
+----------------------+------------+
|     shape_prior      |  0.000078  |
| keypoints3d_limb_len |  0.000873  |
|      total_loss      |  0.000951  |
|  default_optimizer   |  0.000951  |
+----------------------+------------+
2023-02-14 17:52:48,435 - __main__ - INFO - epoch 0, stage 1
2023-02-14 17:52:48,435 - __main__ - INFO - epoch 0, stage 1
2023-02-14 17:52:48,447 - __main__ - WARNING - Args below do not match any loss handler:
+-----------------+-----------+
|     Arg key     | Arg value |
+-----------------+-----------+
| shoulder_weight |    1.0    |
|    hip_weight   |    1.0    |
+-----------------+-----------+
2023-02-14 17:52:48,447 - __main__ - WARNING - Args below do not match any loss handler:
+-----------------+-----------+
|     Arg key     | Arg value |
+-----------------+-----------+
| shoulder_weight |    1.0    |
|    hip_weight   |    1.0    |
+-----------------+-----------+
2023-02-14 17:52:52,314 - __main__ - INFO - [ftol=0.0001] Early stop at 5 iter!
2023-02-14 17:52:52,314 - __main__ - INFO - [ftol=0.0001] Early stop at 5 iter!
2023-02-14 17:52:52,323 - __main__ - INFO - 
+-------------------+------------+
|     Loss name     | Loss value |
+-------------------+------------+
|  keypoints3d_mse  |  0.000424  |
|     total_loss    |  0.000424  |
| default_optimizer |  0.000424  |
+-------------------+------------+
2023-02-14 17:52:52,323 - __main__ - INFO - 
+-------------------+------------+
|     Loss name     | Loss value |
+-------------------+------------+
|  keypoints3d_mse  |  0.000424  |
|     total_loss    |  0.000424  |
| default_optimizer |  0.000424  |
+-------------------+------------+
2023-02-14 17:52:52,324 - __main__ - INFO - epoch 0, stage 2
2023-02-14 17:52:52,324 - __main__ - INFO - epoch 0, stage 2
2023-02-14 17:53:55,483 - __main__ - INFO - [ftol=0.0001] Early stop at 68 iter!
2023-02-14 17:53:55,483 - __main__ - INFO - [ftol=0.0001] Early stop at 68 iter!
2023-02-14 17:53:55,495 - __main__ - INFO - 
+-------------------+------------+
|     Loss name     | Loss value |
+-------------------+------------+
|  keypoints3d_mse  |  0.013497  |
|    smooth_joint   |  0.006068  |
|      pose_reg     |  0.000703  |
|     total_loss    |  0.020268  |
| default_optimizer |  0.020268  |
+-------------------+------------+
2023-02-14 17:53:55,495 - __main__ - INFO - 
+-------------------+------------+
|     Loss name     | Loss value |
+-------------------+------------+
|  keypoints3d_mse  |  0.013497  |
|    smooth_joint   |  0.006068  |
|      pose_reg     |  0.000703  |
|     total_loss    |  0.020268  |
| default_optimizer |  0.020268  |
+-------------------+------------+
```

**Comment by canghaiyunfan** [comment]
Yes, I have download SMC data from [getting_started section](https://github.com/openxrlab/xrmocap/blob/main/docs/en/getting_started.md#single-person)?

p000127_a000007.7z file md5 is 134a0f8544f532e9c0bab0c58d21cd44.

This is my log:
```
python tools/process_smc.py \
> --estimator_config configs/humman_mocap/mview_sperson_smpl_estimator.py \
> --smc_path xrmocap_data/humman/p000127_a000007.smc \
> --output_dir xrmocap_data/humman/p000127_a000007_output \
> --visualize
/home/miniconda3/envs/zy/lib/python3.10/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
2023-02-15 14:39:15,545 - OpenGL.acceleratesupport - INFO - OpenGL_accelerate module loaded
2023-02-15 14:39:15,549 - OpenGL.arrays.arraydatatype - INFO - Using accelerated ArrayDatatype
load checkpoint from local path: weight/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
load checkpoint from local path: weight/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth
WARNING: You are using a SMPL model, with only 10 shape coefficients.
/home/code/xrmocap/xrmocap/io/camera.py:182: UserWarning: Optimal rotation is not uniquely or poorly defined for the given sets of vectors.
  rotation = scipy_Rotation.align_vectors(
2023-02-15 14:39:19,868 - __main__ - WARNING - Overwriting xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames and its files.
2023-02-15 14:39:24,363 - root - WARNING - Overwriting xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_00 and its files.
2023-02-15 14:39:24,363 - __main__ - INFO - Running "ffmpeg -y -f rawvideo -s 1920x1080 -pix_fmt bgr24 -loglevel error -threads 4 -i - -f image2 -start_number 0 xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_00/%06d.png"
2023-02-15 14:39:30,627 - root - WARNING - Overwriting xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_01 and its files.
2023-02-15 14:39:30,627 - __main__ - INFO - Running "ffmpeg -y -f rawvideo -s 1920x1080 -pix_fmt bgr24 -loglevel error -threads 4 -i - -f image2 -start_number 0 xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_01/%06d.png"
2023-02-15 14:39:36,372 - root - WARNING - Overwriting xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_02 and its files.
2023-02-15 14:39:36,372 - __main__ - INFO - Running "ffmpeg -y -f rawvideo -s 1920x1080 -pix_fmt bgr24 -loglevel error -threads 4 -i - -f image2 -start_number 0 xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_02/%06d.png"
2023-02-15 14:39:42,354 - root - WARNING - Overwriting xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_03 and its files.
2023-02-15 14:39:42,355 - __main__ - INFO - Running "ffmpeg -y -f rawvideo -s 1920x1080 -pix_fmt bgr24 -loglevel error -threads 4 -i - -f image2 -start_number 0 xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_03/%06d.png"
2023-02-15 14:39:48,144 - root - WARNING - Overwriting xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_04 and its files.
2023-02-15 14:39:48,145 - __main__ - INFO - Running "ffmpeg -y -f rawvideo -s 1920x1080 -pix_fmt bgr24 -loglevel error -threads 4 -i - -f image2 -start_number 0 xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_04/%06d.png"
2023-02-15 14:39:53,870 - root - WARNING - Overwriting xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_05 and its files.
2023-02-15 14:39:53,870 - __main__ - INFO - Running "ffmpeg -y -f rawvideo -s 1920x1080 -pix_fmt bgr24 -loglevel error -threads 4 -i - -f image2 -start_number 0 xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_05/%06d.png"
2023-02-15 14:39:59,687 - root - WARNING - Overwriting xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_06 and its files.
2023-02-15 14:39:59,687 - __main__ - INFO - Running "ffmpeg -y -f rawvideo -s 1920x1080 -pix_fmt bgr24 -loglevel error -threads 4 -i - -f image2 -start_number 0 xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_06/%06d.png"
2023-02-15 14:40:05,496 - root - WARNING - Overwriting xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_07 and its files.
2023-02-15 14:40:05,496 - __main__ - INFO - Running "ffmpeg -y -f rawvideo -s 1920x1080 -pix_fmt bgr24 -loglevel error -threads 4 -i - -f image2 -start_number 0 xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_07/%06d.png"
2023-02-15 14:40:11,474 - root - WARNING - Overwriting xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_08 and its files.
2023-02-15 14:40:11,474 - __main__ - INFO - Running "ffmpeg -y -f rawvideo -s 1920x1080 -pix_fmt bgr24 -loglevel error -threads 4 -i - -f image2 -start_number 0 xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_08/%06d.png"
2023-02-15 14:40:17,088 - root - WARNING - Overwriting xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_09 and its files.
2023-02-15 14:40:17,089 - __main__ - INFO - Running "ffmpeg -y -f rawvideo -s 1920x1080 -pix_fmt bgr24 -loglevel error -threads 4 -i - -f image2 -start_number 0 xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames/view_09/%06d.png"
2023-02-15 14:40:59,344 - __main__ - INFO - Estimating keypoints2d.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:06<00:00,  1.42it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 393354.12it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:05<00:00,  1.77it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 453576.01it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  1.93it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 387233.46it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  1.90it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 431054.34it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  1.90it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 436600.07it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  1.81it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 371066.66it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  1.88it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 416157.25it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  1.92it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 449209.45it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  1.88it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 437623.75it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  1.90it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 356195.66it/s]
2023-02-15 14:41:48,875 - __main__ - INFO - Estimating keypoints3d.
2023-02-15 14:41:48,875 - __main__ - ERROR - No one has been detected in any view.
Traceback (most recent call last):
  File "/home/code/xrmocap/tools/process_smc.py", line 214, in <module>
    main(args)
  File "/home/code/xrmocap/tools/process_smc.py", line 76, in main
    keypoints2d_list, keypoints3d, smpl_data = mview_sp_smpl_estimator.run(
  File "/home/code/xrmocap/xrmocap/core/estimation/mview_sperson_smpl_estimator.py", line 232, in run
    keypoints3d = self.estimate_keypoints3d(
  File "/home/code/xrmocap/xrmocap/core/estimation/mview_sperson_smpl_estimator.py", line 330, in estimate_keypoints3d
    raise AttributeError
AttributeError
```

**Comment by LazyBusyYang** [comment]
By reading the log
`100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 416157.25it/s]`
We know that keypoints2d estimation takes zero time. There's no kps2d data in anyview. Shall we check the input images `in xrmocap_data/humman/p000127_a000007_output/p000127_a000007_temp_frames` and bbox output of mmdet?

**Comment by canghaiyunfan** [comment]
The bbox output of mmdet is None. My mmdet version is 2.28.1

**Comment by LazyBusyYang** [comment]
It seems a problem caused by mmdet update.
In one of our released docker image, versions of packages are listed below:
```
pytorch                   1.12.0          py3.8_cuda11.3_cudnn8.3.2_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytorch3d                 0.7.2           py38_cu113_pyt1120    pytorch3d
torchvision               0.13.0               py38_cu113    pytorch
mmcls                     0.25.0                   pypi_0    pypi
mmcv-full                 1.6.1                    pypi_0    pypi
mmdeploy                  0.12.0                    dev_0    <develop>
mmdet                     2.27.0                   pypi_0    pypi
mmhuman3d                 0.10.0                    dev_0    <develop>
mmpose                    0.29.0                   pypi_0    pypi
mmtrack                   0.14.0                   pypi_0    pypi
```
Please install them according these, or directly use our docker image `openxrlab/xrmocap_runtime:ubuntu1804_x64_cu114_py38_torch1120_mmcv161`.
 To test whether our environmet works well, you can run `pytest tests/`, and there should be no failed cases.

**Comment by LazyBusyYang** [comment]
This issue is closed because it has been inactive for 7 days since being marked as stale. Feel free to re-open it if the problem is not solved.

**Comment by RuiZhang-USTC** [comment]
> ```
> 2023-02-13 16:06:36,471 - __main__ - INFO - Estimating keypoints3d.
> 2023-02-13 16:06:36,471 - __main__ - ERROR - No one has been detected in any view.
> Traceback (most recent call last):
>   File "/home/code/xrmocap/tools/process_smc.py", line 214, in <module>
>     main(args)
>   File "/home/code/xrmocap/tools/process_smc.py", line 76, in main
>     keypoints2d_list, keypoints3d, smpl_data = mview_sp_smpl_estimator.run(
>   File "/home/code/xrmocap/xrmocap/core/estimation/mview_sperson_smpl_estimator.py", line 232, in run
>     keypoints3d = self.estimate_keypoints3d(
>   File "/home/code/xrmocap/xrmocap/core/estimation/mview_sperson_smpl_estimator.py", line 330, in estimate_keypoints3d
>     raise AttributeError
> AttributeError
> ```
> 
> cmd
> 
> ```
> python tools/process_smc.py \
> 	--estimator_config configs/humman_mocap/mview_sperson_smpl_estimator.py \
> 	--smc_path xrmocap_data/humman/p000127_a000007.smc \
> 	--output_dir xrmocap_data/humman/p000127_a000007_output \
> 	--visualize
> ```


the dataset google drive link is unavailable, could you pls share the data: 
p000127_a000007.7z

**Comment by yl-1993** [comment]
@RuiZhang-USTC We have updated the data example. You can

1. Download a data example [p000455_a000986.smc](https://openxdlab.oss-cn-shanghai.aliyuncs.com/HuMMan/humman_release_v1.0_recon_smc/p000455_a000986.smc)
2. Run with
```bash
python tools/process_smc.py \
	--estimator_config configs/humman_mocap/mview_sperson_smpl_estimator.py \
	--smc_path xrmocap_data/humman/p000455_a000986.smc \
	--output_dir xrmocap_data/humman/p000455_a000986_output \
	--visualize
```

Please see [this commit](https://github.com/openxrlab/xrmocap/commit/4039369916c79f9ae6252078dc55bc521402003e) for more details.
